### ISSUE TITLE
Organize sometimes imports produces wrong imports

### ISSUE THREAD

**Issue by dbo** [eclipse/n4js#1487] opened 2019-09-24 07:14 UTC
Sorry, no reproducable example, but I sometimes get

`import ... from "@n4jsd/...";`

or

`import {ReduxAction} from "lib/redux";`

or

`import * as React from "index";`

imports applying organize imports on a source file. However, the transpiled import statement looks fine.

**Comment by mor-n4** [comment] 2020-04-28 11:39
Closing this as duplicate of #1203.

**Closed** 2020-04-28 11:40 UTC
Labels: bug, duplicate
