### ISSUE TITLE
All N4JSIDE / Eclipse menu items disabled after upgrade to HighSierra

### ISSUE THREAD

**Issue by yoosiba** [eclipse/n4js#325] opened 2017-10-27 09:41 UTC
@kduske-n4 says

> After upgrading to High Sierra, all menu items in Eclipse (incl. N4JSIDE) were disabled. This is a known problem if the system language is not english:
> 
> https://bugs.eclipse.org/bugs/show_bug.cgi?id=519724
> 
> Workarounds include changing the system language to english and removing some entries from the app bundle’s Info.plist:
> 
> https://bugs.eclipse.org/bugs/show_bug.cgi?id=519724#c14

Maybe this won't be fixed  directly in n4js, but it is worth to have a ticket to track tis issue.
Eclipse will take care of platform fix, but some hot fixing might be possible/needed for n4js.

**Comment by yoosiba** [comment] 2018-06-08 08:38
@kduske-n4  is it still an issue in current IDE and OSX?

**Comment by kduske-n4** [comment] 2018-06-08 08:50
I could not reproduce it on High Sierra with a current IDE.

**Comment by mmews-n4** [comment] 2018-10-23 14:18
Since we all use High Sierra without any problems as far as I know, I this this issue does not exist anymore. Closing this as invalid.

**Closed by mmews-n4** 2018-10-23 14:18 UTC
Labels: bug
