### ISSUE TITLE
Exception when updating libraries due to problem with package.json

### ISSUE THREAD

**Issue by jpilgrim** [eclipse/n4js#727] opened 2018-04-12 15:02 UTC
Exception in library manager ("Install missing dependencies"):
```
[12-04-2018 04:58:04] java.io.IOException: Cannot read package.json content for package 'package.json' at workspace/.metadata/.plugins/org.eclipse.n4js.external.libraries/.n4npm/node_modules/eu.numberfour.stdlib.model.gen/package.json'.
	at org.eclipse.n4js.external.NpmPackageToProjectAdapter.getPackageJson(NpmPackageToProjectAdapter.java:207)
	at org.eclipse.n4js.external.NpmCLI.getActualVersion(NpmCLI.java:176)
	at org.eclipse.n4js.external.NpmCLI.installUninstall(NpmCLI.java:151)
	at org.eclipse.n4js.external.NpmCLI.batchInstallUninstallInternal(NpmCLI.java:122)
	at org.eclipse.n4js.external.NpmCLI.batchInstall(NpmCLI.java:104)
	at org.eclipse.n4js.external.LibraryManager.installUninstallNPMs(LibraryManager.java:220)
	at org.eclipse.n4js.external.LibraryManager.installNPMsInternal(LibraryManager.java:196)
	at org.eclipse.n4js.external.LibraryManager.lambda$2(LibraryManager.java:180)
	at org.eclipse.n4js.external.LibraryManager$$Lambda$501/1337345395.get(Unknown Source)
	at org.eclipse.n4js.external.LibraryManager.runWithWorkspaceLock(LibraryManager.java:492)
	at org.eclipse.n4js.external.LibraryManager.installNPMs(LibraryManager.java:180)
	at org.eclipse.n4js.ui.external.ExternalLibrariesActionsHelper.installNoUpdate(ExternalLibrariesActionsHelper.java:132)
	at org.eclipse.n4js.ui.handler.LibrariesFixHandler.calculateAndInstallDependencies(LibrariesFixHandler.java:182)
	at org.eclipse.n4js.ui.handler.LibrariesFixHandler.setupWorkspaceDependnecies(LibrariesFixHandler.java:156)
	at org.eclipse.n4js.ui.handler.LibrariesFixHandler$1.run(LibrariesFixHandler.java:75)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)
```

**Comment by mmews-n4** [comment] 2018-10-23 13:55
Cannot reproduce this. Also the library manager was refactored and (hopefully) improved a lot in the last month. Closing this as invalid.

**Closed by mmews-n4** 2018-10-23 13:55 UTC
Labels: bug, prio-high
