### ISSUE TITLE
As a user I want to use '_' in regular expression CharacterClass 

### ISSUE THREAD

**Issue by szarnekow** [eclipse/n4js#1725] opened 2020-04-20 12:46 UTC
Make this test pass:
(ParserTest.xtend in regex package)
```
	@Test
	def void test_43() {
		'''/[_]/'''.assertValid
	}
```

**Comment by mor-n4** [comment] 2020-07-21 08:21
Is this a duplicate of #1686? (or vice versa)

**Comment by szarnekow** [comment] 2020-07-21 08:41
Yes, it is.

**Comment by mor-n4** [comment] 2020-07-21 08:48
Thanks!

Closing this as duplicate.

**Closed by mor-n4** 2020-07-21 08:48 UTC
Labels: duplicate
