### ISSUE TITLE
N4JS Editor Markers and Problems View Issues are not always in sync

### ISSUE THREAD

**Issue by lbeurerkellner** [eclipse/n4js#241] opened 2017-09-19 10:25 UTC
It is possible to create a situation in which the N4JS Editor of a N4JS file that contains errors does not show all/any markers although the Problems View lists of all of the issues as expected.

There is not yet a definitive way to reproduce this but this issue should serve to collect situations in which we experienced such issues.

**Comment by lbeurerkellner** [comment] 2017-09-19 10:29
While working on a task, were it was necessary to create issues by manually specifying offset and length, I could provoke such a situation.

In my case this was due to a programming mistake by my side. If an issue is created for an offset and length for which offset + length > file length, the editor won't show an error for this issue. The Problem View, however, will look as expected, since the Location column there is solely depends on the correct offset and doesn't care about the issue length.

It is important to note that when adding issue at a manual offset that the length is always relative to the offset.

**Comment by mor-n4** [comment] 2018-01-23 14:34
@lbeurerkellner Is there anything we can reproduce or at least concrete issues we know of?

If we haven't found anything concrete since Sep 19, last year, we should close this, for now.

**Comment by mmews-n4** [comment] 2018-10-23 14:30
Good insights and advice!

I agree to close the issue since it was not witnessed as far as I know.

**Closed by mmews-n4** 2018-10-23 14:30 UTC
Labels: bug
