### ISSUE TITLE
As a developer I want better validation for the explicit declaration of versions in N4IDL

### ISSUE THREAD

**Issue by lbeurerkellner** [eclipse/n4js#524] opened 2018-02-01 13:33 UTC
For now, it is allowed to explicitly declare versions of type references everywhere.
However, the idea is that only migrations have to deal with explicit versions of types.
In all other places, the inferred context version is supposed to specify the type versions.

Thus, as part of this issue, validation should be introduced, enforcing this concept.

Furthermore, unversioned type declarations should be fully disallowed in N4IDL files.

**Comment by lbeurerkellner** [comment] 2018-02-22 12:17
This issue is a duplicate of #605 and can therefore be closed.

**Comment by mor-n4** [comment] 2018-02-26 12:20
closing as duplicate of https://github.com/eclipse/n4js/issues/605

**Closed by mor-n4** 2018-02-26 12:20 UTC
