### ISSUE TITLE
Too many manual steps when upgrading ide

### ISSUE THREAD

**Issue by arrowplum** [eclipse/n4js#236] opened 2017-09-14 10:33 UTC
From https://github.com/NumberFour/n4js/issues/418
The process to upgrade the IDE (which we generally do daily)

Update:

1. Run all N4JS external libraries/maintenance actions (triggers rebuild even if build turned off) and find errors
2. Run second and third maintenance actions again (another rebuild)
3. Re import express library via quick fix in manifest file (another rebuild)
4. build clean.

This should be limited to:

1. Update (with one build clean)

**Comment by mor-n4** [comment] 2018-01-23 14:38
closing as duplicate of #429

**Closed by mor-n4** 2018-01-23 14:38 UTC
