### ISSUE TITLE
As a smith I want to reconsider Shipped Code and the concept of Shadowing

### ISSUE THREAD

**Issue by mmews-n4** [eclipse/n4js#1259] opened 2019-02-21 16:04 UTC
**Shipped Code**
Shipped code are n4js libraries within the IDE and provide type information and / or runtime behavior without separately installing. As a result, the node_modules folder of an n4js project does not need to be populated with shipped code libraries, since the IDE copes for that. However, executing the very same n4js project on the command line will fail (e.g. using node.js) since its node_modules folder is not populated with the shipped code libraries.
=> That is why reconsidering shipped code is necessary.

**Shadowing**
Shadowing fulfills the following two use-cases:
1) A user workspace project with the name of a shipped code project will hide the shipped code project and hence be used for supplying type information and runtime behavior.
2) Given there are two projects P1 and P2 where each of them has a node_modules folder NM1 and NM2. Further given that both of the node_modules folders an npm is installed that has the same name, e.g. 'lodash'. At the moment, the type index of N4JS can contain only one package of the same name at once. Hence, 'lodash' of NM2 will shadow 'lodash' of NM1 (shadowing is resolved alphabetically).

=> Since shipped will probably be removed, case 1) of shadowing will be obsolete.

**Comment by mor-n4** [comment] 2019-05-14 09:44
Closing this as duplicate of `GH-877` and (the newer) `GH-1314`.

**Closed by mor-n4** 2019-05-14 09:44 UTC
Labels: userstory
